import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import gradient from "@/public/gradient.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image
          className="-z-10"
          src={gradient}
          alt="Gradient background"
          placeholder="blur"
          quality={100}
          fill
          sizes="100vw"
          style={{
            objectFit: "cover",
            filter: "brightness(0.95);",
          }}
        />
        <span className="text-white w-full font-serif font-bold text-center text-2xl block mt-2">
          <Link href="/">pdbr</Link>
        </span>
        {children}
      </body>
    </html>
  );
}
